apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.bluemix.net/rewrite-path: "serviceName=acmeair-customer-service rewrite=/"
  name: acmeair-customer-ingress
spec:
  rules:
  - host: INGRESS_URL
    http:
      paths:
      - path: /customer
        backend:
          serviceName: acmeair-customer-service
          servicePort: 9080
